### ISSUE TITLE
vertical range

### ISSUE THREAD

**Issue by rubenarslan** [aFarkas/webshim#519]
Is it possible to make ranges vertical? I found [this](https://stackoverflow.com/questions/15935837/how-to-display-a-range-input-slider-vertically) which makes the native ranges vertical, but webshim does not seem to pick up on the height being greater than the width or any of the other cues.

**Comment by aFarkas** [comment]
You can try this:

```css
.ws-range,
 input[type="range"] {
    width: 0.61538em;
    height: 199px;
}
```
But this CSS should be in sync with this js config:

```js
webshim.setOptions('forms-ext', {
    replaceUI: true
});
```

[Demo http://jsfiddle.net/trixta/2v1vmgyx/](http://jsfiddle.net/trixta/2v1vmgyx/)

**Comment by rubenarslan** [comment]
I added


```css
.ws-range
 .ws-range-thumb {
	 margin-left:-4.5px !important;
}
```

so that the thumb would not be left-shifted at load. It does return to the correct position once you drag it, but it starts at `margin-left:-11px`. Will this have unforeseen side effects?
http://jsfiddle.net/f6rt1nzw/1/

**Comment by aFarkas** [comment]
No, but the idea of the inline margin-left/margin-top is that it always tries to center the thumg inside the range. In case you don't want to center it, you can/should use top/left instead:

```css
 .ws-range-thumb {
	 left: 8px;
}
``` 
[Demo: http://jsfiddle.net/trixta/f6rt1nzw/2/](http://jsfiddle.net/trixta/f6rt1nzw/2/)
